[pytest]
addopts =
    -s
    -v
    --junitxml=reports/junit.xml
    --html=reports/report.html
junit_family = xunit2
log_cli = true
log_cli_level = INFO
log_file = reports/pytest.log
log_file_level = INFO