[tox]
envlist = black, flake8

[testenv:black]
description = Run Black code formatter
skip_install = true
deps = black
commands = black --check --diff --line-length 120 .

[testenv:flake8]
skip_install = true
deps = flake8
commands = flake8 .

[flake8]
max-line-length = 120

exclude =
    .tox,
    .git,
    __pycache__,
    .venv,
    venv,
    .githu