name: validate-tox
on:
  push:
jobs:
  tox:
    uses: ./.github/workflows/setup-base.yml
    permissions:
      checks: write
      pull-requests: write
      contents: read
    with:
      run-tox: true