name: system-tests
on:
  push:
jobs:
  validate-system-tests:
    uses: ./.github/workflows/setup-base.yml
    permissions:
      checks: write
      pull-requests: write
      contents: read
    secrets: inherit
    with:
      run-tox: false
      run-system-tests: true